### ISSUE TITLE
Add package to AUR

### ISSUE THREAD

**Issue by 1nikolas** [JezerM/web-greeter#11]
Hello, it would be useful to add this fork on [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) since it's the current active fork of web-greeter and many people use the original outdated package. [Here](https://wiki.archlinux.org/title/AUR_submission_guidelines) is some info on how to submit a package on AUR (basically there should only be a [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) file on the AUR repo which clones this repo and runs the necessary commands).
Thanks

**Comment by JezerM** [comment]
Hi, thanks for the comment. I had some plans to add this fork to AUR, but I've been busy with college. Therefore, it will take some time to make this possible~
