### ISSUE TITLE
Needs password change function for expired accounts

### ISSUE THREAD

**Issue by ulkuderner** [JezerM/web-greeter#13]
It would be great to have a change password option for expired passwords on directory service like unity-greeter

**Comment by JezerM** [comment]
Could you elaborate this? I can't make **unity-greeter** to work and never used it before, so I don't know what you mean~

**Comment by JezerM** [comment]
I don't think that's actually possible with LightDM, as this is mainly just a way to login to your Linux desktop.

Services like Samba wouldn't be shown in LightDM users section (unless you specify it inside `/etc/lightdm/lightdm.conf`). And even if you do, it will log you in a Session with that user, which wouldn't be convenient. It won't ask you for a new password, so it's less convenient.

Also, there's no way to check if a user password is expired with LightDM while this is inactive (when you are inside a Session). Therefore, this won't prompt for expired passwords when they expire.

Maybe, Unity has this feature as a DE, and some other DEs do something similar. But I guess this feature is out of the scope of LightDM.
