### ISSUE TITLE
Can't not make install due to file error

### ISSUE THREAD

**Issue by metropolis-nostalgia** [JezerM/web-greeter#14]
## Environment
- OS: Debian GNU/Linux 11
- web-greeter version: Not install yet

## Bug description
`make install` exit with an error
This is its output:
```
root@debian:~/web-greeter# make install
./build/utils.sh clean
./build/utils.sh build-init
./build/utils.sh build /usr
Building web-greeter with cx_freeze...
setup.py log inside /root/web-greeter/build/setup_log
mv: cannot stat '/root/web-greeter/build/web-greeter/dist/*': No such file or directory
make: *** [Makefile:65: build] Error 1
```

## Steps to reproduce
Steps to reproduce the behaviour:
```
git clone https://github.com/JezerM/web-greeter.git
cd web-greeter
sudo pip install -r requirements.txt
sudo make install
```

## Expected behavior
`make install` will exit with a successful message and web greeter will work.

## **Screenshots**
![make error](https://user-images.githubusercontent.com/82685767/138562457-c3019ffb-fc3e-4b8a-bcb2-5a85f1bfba33.png)
(I edit my XFCE theme)

**Comment by JezerM** [comment]
I changed the installation method because it was causing lots of errors, so now it should work, I guess :D

Use `sudo make install` and it should be enough. Use `sudo make install_freeze` if you wanna use **cx_freeze** to build **web-greeter**.

**Comment by WildEgo** [comment]
> I changed the installation method because it was causing lots of errors, so now it should work, I guess :D
> 
> Use `sudo make install` and it should be enough. Use `sudo make install_freeze` if you wanna use **cx_freeze** to build **web-greeter**.

I'll give it a try as soon as I have some more free time, I can now test it on bare metal since I've moved to Linux as my daily driver

**Comment by WildEgo** [comment]
Ok so I managed to install it and it feels pretty amazing, only thing is that I need zip and I honestly fully had forgotten to install it personally just add it on the Dependencies tab so other people don't find the same problem.

**Comment by metropolis-nostalgia** [comment]
First, I am using the Bash shell prompt, as root (I don't have sudo).
Second, I found a way to use my GTK theme as the greeter theme without error, so I don't need a web-greeter theme.
Feels free to reopen it in case another user found this problem again.
