### ISSUE TITLE
had to install patchelf as a dependency which was not specified

### ISSUE THREAD

**Issue by trwnh** [JezerM/web-greeter#16]
## Environment
- OS: Arch
- web-greeter version: `web-greeter` not found

## Bug description
The build fails if `patchelf` is not installed.

## Steps to reproduce
Try to build on Arch

## Expected behavior
Build is successful

**Comment by JezerM** [comment]
Yeah, I also think `cx_freeze` should be specified as a dependency.

**Comment by JezerM** [comment]
I just updated the README~
