### ISSUE TITLE
`web-greeter` binary does not build or install

### ISSUE THREAD

**Issue by trwnh** [JezerM/web-greeter#17]
## Environment
- OS: Arch
- web-greeter version: `web-greeter` not found

## Bug description
The `web-greeter` binary does not seem to be built or generated, let alone copied to the right place

## Steps to reproduce
Try to build on Arch using the instructions

## Expected behavior
Binary is built successfully

**Comment by JezerM** [comment]
Could you provide the terminal output? Also, provide the cx_freeze log found inside `./build/setup_log`.

**Comment by Franguestclain** [comment]
@trwnh make sure to have patchelf installed, I just ran into the same problem and that solved the issue :smiley:

**Comment by Franguestclain** [comment]
@JezerM Also I think there is a problem, I just tried to run `web-greeter --debug` and the command wasn't found, so I run `which web-greeter` to know where it was the binary and also it wasn't found. Then I search in `/usr/bin/` and the symlink points to `//opt/web-greeter/web-greeter`.

If I'm wrong, then tell me why it isn't working, please xD

**Comment by JezerM** [comment]
@Franguestclain `web-greeter` is a symlink to `/opt/web-greeter/web-greeter`, which should be installed when you do `sudo make install`. So, maybe it wasn't installed? Or was it deleted?

If you see any problem, you may prefer to install it with `sudo make install_old`.

**Comment by Franguestclain** [comment]
The thing is that the symlink has double `/`
![image](https://user-images.githubusercontent.com/25850692/141696748-7e093e95-ff30-4256-a789-04f9e4da507c.png)

So, do I need to delete the things that I already installed? (If i need to run `sudo make install_old`). If yes, how do I remove the previous install? (noob with packages compiled from source)

**Comment by JezerM** [comment]
Well, yeah, you could remove the `/opt/web-greeter/` directory, and `/usr/bin/web-greeter` as well. There is no `uninstall` rule in the `Makefile`, so it's not "easy" to uninstall it... I should create a rule for that.

The `web-greeter` install method is a mess xd

**Comment by JezerM** [comment]
Added a **uninstall** rule, so just run `sudo make uninstall` and it should uninstall everything, except the themes and the configuration.

Aditionally, the installation method is not the zippy way, so there should not be any problem with `cx_freeze` now, unless you do `sudo make install_freeze` for an "static" installation.

**Comment by trwnh** [comment]
one other missing dependency not listed in the readme: `gobject-introspection`

**Comment by trwnh** [comment]
works now, i think? i now have `/usr/bin/web-greeter` successfully existing. here's what i did (simplified/corrected):

```
cd ~/build
pacman -S needed lightdm python-gobject python-pyqt5 qt5-webengine gobject-introspection patchelf
git clone https://github.com/JezerM/web-greeter.git
cd web-greeter
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
sudo make install
```

this issue can be closed after adding these instructions to readme and adding `gobject-introspection` as a dependency :)

**Comment by trwnh** [comment]
actually running `web-greeter --debug` now prints the following after crashing:

```
$ web-greeter --debug
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
2021-11-16 04:22:15 [ DEBUG ] screensaver - screensaver.py:30 : set_screensaver | Screensaver timeout set
2021-11-16 04:22:15 [ DEBUG ] browser - browser.py:204 : init | Initializing Browser Window

DevTools listening on ws://127.0.0.1:12345/devtools/browser/9368b9d0-91ba-44c5-840d-28828aae2f18
NotImplementedError: QLayout.count() is abstract and must be overridden
NotImplementedError: QLayout.itemAt() is abstract and must be overridden
2021-11-16 04:22:16 [ DEBUG ] browser - browser.py:274 : _initialize_devtools | DevTools initialized
2021-11-16 04:22:16 [ DEBUG ] browser - browser.py:245 : init | Browser Window created
2021-11-16 04:22:16 [ DEBUG ] browser - browser.py:156 : show | Window is ready
2021-11-16 04:22:16 [ DEBUG ] browser - browser.py:335 : load_theme | Theme loaded
2021-11-16 04:22:16 [ ERROR ] Greeter.py 152 : __init__ | lightdm_greeter_error: Unable to determine socket to daemon (1)
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:12345
2021-11-16 04:22:16 [ ERROR ] userscript:Web Greeter Bundle 250: Uncaught ReferenceError: QWebChannel is not defined
Traceback (most recent call last):
  File "/usr/bin/web-greeter/bridge/Greeter.py", line 150, in __init__
gi.repository.GLib.Error: lightdm_greeter_error: Unable to determine socket to daemon (1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/web-greeter/browser/error_prompt.py", line 88, in javaScriptConsoleMessage
  File "/usr/bin/web-greeter/browser/error_prompt.py", line 117, in errorPrompt
AttributeError: module 'globals' has no attribute 'greeter'
Aborted (core dumped)
```

we examine the coredump using coredumpctl and see a bunch of "found module" lines; at the end is this stack trace

```
Stack trace of thread 120690:
                #0  0x00007fe9d443ad22 raise (libc.so.6 + 0x3cd22)
                #1  0x00007fe9d4424862 abort (libc.so.6 + 0x26862)
                #2  0x00007fe9d1ac59bc n/a (/home/trwnh/build/web-greeter/venv/lib/python3.9/site-packages/PyQt5/Qt5/lib/libQt5Core.so.5 + 0x929bc)
                #3  0x0000000000000000 n/a (n/a + 0x0)
```

**Comment by JezerM** [comment]
First, you're using wayland, while `web-greeter` was created and tested on **X11**. Maybe try to use another WM/DE?

Second, `web-greeter` is unable to connect to LightDM, which could mean two things:
- LightDM libraries are not installed (like gobject-introspection xd)
- Your session does not allow using LightDM. See [here](https://github.com/JezerM/web-greeter#Debugging). Add this line to your **xsession**, log out and log in: `X-LightDM-Allow-Greeter=true`

**Comment by trwnh** [comment]
hmm, did not know wayland would be an issue. i am currently in gnome, but can test again in xfce if that would make a difference. out of curiosity, do you know which lightdm libraries should be installed? my hope in trying to follow the installation instructions for this project is to make builds reproducible and improve the documentation, and also as a learning experience. a quick pacman/yay search for `lightdm` shows `liblightdm-qt5` is not installed, might that be necessary? i'll try installing that if switching to x11 doesn't work.

**Comment by trwnh** [comment]
spoiler alert: `nody-greeter --debug` works fine in gnome/wayland, so that might not be it :p

**Comment by JezerM** [comment]
> nody-greeter --debug works fine in gnome/wayland

Oh, noted~

> do you know which lightdm libraries should be installed?

I can't tell right now, until I get home. But some dependencies might be `liblightdm-gobject-1-dev`, and `libgirepository1.0-dev`

**Comment by trwnh** [comment]
`web-greeter --debug` still crashes in the exact same way on x11, confirmed

**Comment by trwnh** [comment]
also the double-slash issue is because of $DESTDIR being / -- I don't think this *technically* breaks the links, but it is a bit weird and could be sanitized https://github.com/JezerM/web-greeter/blob/4af692677ac1f7ed3d3887a551d9d6a9e6f98aa0/build/utils.sh#L51-L55

it would probably take either a check for $DESTDIR == /, or removing the slashes after DESTDIR, or search-and-replace the final path to turn // into /

**Comment by JezerM** [comment]
Try this, and check if it does work:

```sh
cd web-greeter/
python3 . --debug
```

If it does, pip libraries are not installed globally, but with venv; so, you would need to install these dependencies globally.

If it does not work, then... we are in the same problem.

**Comment by trwnh** [comment]
yep, doesn't work. same problem

**Comment by JezerM** [comment]
After checking your log, the problem may be **qt5webengine**, as `QWebChannel is not defined`. Even if it's `Unable to determine socket to daemon`, web-greeter should start correctly. I'll try to run Arch and see how to solve this problem.

**Comment by trwnh** [comment]
hmm, doing a quick search in the repos for webengine, i see that i have `qt5-webengine` installed but not `python-pyqt5-webengine` -- i'll try installing that and see if that fixes it

**Comment by trwnh** [comment]
nope :( getting these new lines from the --debug output, though:
```
NotImplementedError: QLayout.count() is abstract and must be overridden
NotImplementedError: QLayout.itemAt() is abstract and must be overridden
```

still the same traceback about `AttributeError: module 'globals' has no attribute 'greeter'` though

**Comment by JezerM** [comment]
These “errors”, should not interfere with web-greeter:

```
NotImplementedError: QLayout.count() is abstract and must be overridden
NotImplementedError: QLayout.itemAt() is abstract and must be overridden
```

Though, it’s still something to fix.

**Comment by trwnh** [comment]
i'm wondering what `AttributeError: module 'globals' has no attribute 'greeter'` means, because it seems to be the most relevant line of the log

**Comment by JezerM** [comment]
The `globals` module has the `greeter` attribute, which is the **Browser**. However, the Browser is never created because of the previous exceptions, and so `globals.greeter` is undefined.

**Comment by JezerM** [comment]
I ran Manjaro inside a VM, and tried to fix this problem.

First, if you have any import error, I suggest to also install `pyqt5` with pacman. I'll add this to README.

Then, it seems `qwebchannel.js` was being loaded after the theme, so the connection between web-greeter and LightDM would be impossible. Therefore, I moved the load_theme after qwebchannel is loaded. You could try this PR, and see if it's solved.

**Comment by trwnh** [comment]
it works now! the pr was the only change needed. `pyqt5` was not necessary. `gobject-introspection`, however, *was* necessary, as stated some comments above in the chain. the NotImplementedErrors also stopped happening as a result of the pr.
