### ISSUE TITLE
web-greeter keeps on restarting in fedora 34

### ISSUE THREAD

**Issue by Root-voidX** [JezerM/web-greeter#19]
Hello,

So i built web-greeter no problem. Running web-greeter in debug mode loads the greeter fine, but if I replace the greeter-session option in the lighdm.conf file, light dm keeps looping, like it stays on a black screen, but i notice my curson go from pointer to spinner constantly, I tried to log in via ttyl but i keep getting kicked because lightdm keeps boot looping. I set my greeter session to web-greeter.

Anyone know why this is? I have the same issue in plasma x11 and gnome x11

**Comment by JezerM** [comment]
Could you provide the log inside `/var/log/lightdm/seat0-greeter.log`?

**Comment by Root-voidX** [comment]
> Could you provide the log inside `/var/log/lightdm/seat0-greeter.log`?

![image](https://user-images.githubusercontent.com/24353606/142337393-12cd5758-0a33-4e88-97b7-a233446db09a.png)

**Comment by Root-voidX** [comment]
it has nothing else in the log

**Comment by JezerM** [comment]
Wow, that's empty... It should at least show some errors.

Could you provide also `/var/log/lightdm/lightdm.log`?

Normally, this happens because of the greeter just crashing and LightDM trying to run the greeter over and over again.

So, from what you said, it works on a session, but not from LightDM. That means the python dependencies are only available from the user, but not from the root.

Therefore, you could try to install the python dependencies globally, with `sudo`, if they aren't.

**Comment by Root-voidX** [comment]
> Wow, that's empty... It should at least show some errors.
> 
> Could you provide also `/var/log/lightdm/lightdm.log`?
> 
> Normally, this happens because of the greeter just crashing and LightDM trying to run the greeter over and over again.
> 
> So, from what you said, it works on a session, but not from LightDM. That means the python dependencies are only available from the user, but not from the root.
> 
> Therefore, you could try to install the python dependencies globally, with `sudo`, if they aren't.
![image](https://user-images.githubusercontent.com/24353606/142347020-8d006d8b-62e5-4001-b41a-60beae1f099d.png)

I did run the requirement.py via sudo. I copied and pasted the command in readme

**Comment by Root-voidX** [comment]
> Wow, that's empty... It should at least show some errors.
> 
> Could you provide also `/var/log/lightdm/lightdm.log`?
> 
> Normally, this happens because of the greeter just crashing and LightDM trying to run the greeter over and over again.
> 
> So, from what you said, it works on a session, but not from LightDM. That means the python dependencies are only available from the user, but not from the root.
> 
> Therefore, you could try to install the python dependencies globally, with `sudo`, if they aren't.

Here is the debug working:

![image](https://user-images.githubusercontent.com/24353606/142347390-472ab0f6-a2c1-4ae9-8649-94249e4d14d0.png)

**Comment by JezerM** [comment]
Hmm... Try to run web-greeter as root, and provide the errors.

> NOTE: `--no-sandbox` error is expected with root

**Comment by Root-voidX** [comment]
> Hmm... Try to run web-greeter as root, and provide the errors.
> 
> > NOTE: `--no-sandbox` error is expected with root

I get this error:

![image](https://user-images.githubusercontent.com/24353606/142718810-59af834f-ad2c-4d56-9597-f126e0c13b8a.png)

It doesnt even open up a debug window

**Comment by JezerM** [comment]
Wow... Sadly, there's no information I can rely on to help you. It works fine on user, but not on LightDM and root. So, it could be that some things aren't installed globally and so web-greeter crashes. However, you said everything is installed, and on root too.

The information you provided me is not so helpful. If you want to give helpful info, follow these steps:

- Set `greeter-session=web-greeter` inside `/etc/lightdm/lightdm.conf`
- Open a VT, like VT1 or VT2, log in with your user or root, and prepare one of these commands (with root privilegies):
    - `systemctl stop lightdm.service`
    - `service lightdm stop`
- Restart `lightdm.service` from your actual session (this will close your session).
- Wait some seconds until you see LightDM trying to run web-greeter over and over again.
- Open your VT and run one of the previous commands to stop LightDM. This will allow you to navigate freely without LightDM interrupting you.
- Go to `/var/log/lightdm` and copy these files (or the entire directory) to your home directory or wherever you want:
    - `lightdm.log`
    - `seat0-greeter.log`
- Change your `greeter-session` to some greeter that actually works, and restart lightdm.

After you log in to your session, check the log you copied and provide it here. These logs will contain the actual behavior of LightDM and all the errors web-greeter could have.

**Comment by JezerM** [comment]
Tried Fedora inside a VM, and web-greeter didn't work. Seems the problem is Qt5-WebEngine, which fails at:

https://github.com/JezerM/web-greeter/blob/75454e1b3b2593d6616839886fa920961d8b36a3/web-greeter/browser/browser.py#L220

However... I don't know why this happens. web-greeter works when logged in inside Fedora with `web-greeter --debug`, and also with `lightdm --test-mode`, but not with LightDM itself.

For now, I don't know how to fix this issue :c

**Comment by JezerM** [comment]
Hi, @Root-voidX, finally after a long time, I found the cause of the problem. Turns out that Fedora runs the LightDM environment with root privilegies, which breaks everything since browsers can't run as root. So I just added a simple patch that forces web-greeter to run with the `--no-sandbox` flag if you're using Fedora.

You could try to build the latest commit in the master branch 60f0d1f9c87f5bf6c91a0c27e50d37383360bdbd, and tell me if it works~

**Comment by Root-voidX** [comment]
> Hi, @Root-voidX, finally after a long time, I found the cause of the problem. Turns out that Fedora runs the LightDM environment with root privilegies, which breaks everything since browsers can't run as root. So I just added a simple patch that forces web-greeter to run with the `--no-sandbox` flag if you're using Fedora.
> 
> You could try to build the latest commit in the master branch [60f0d1f](https://github.com/JezerM/web-greeter/commit/60f0d1f9c87f5bf6c91a0c27e50d37383360bdbd), and tell me if it works~

Hey sorry for the delay, I will try it with new commit. Thanks for looking into it. This should work on latest fedora too =)

**Comment by ghost** [comment]
So i have tried it myself on fedora-asashi 

it seems to work partially, i was able to install all dependencies besides pygobject3.
then i had to install all git sub modules and could build it.

when opening lightdm inside of hyprland I get the error:
`lightdm_greeter_error: Unable to determine socket to daemon (1)` which may be a problem with QT, but else it works fine there.

After setting the greeter with:
`greeter-session=web-greeter`
I get a black screen on startup, when I try to manually execute lightdm in tty it works, but it doesn't boot me into the DE instead restarts lightdm.
