### ISSUE TITLE
WindowsXP theme does not work

### ISSUE THREAD

**Issue by rocheston** [JezerM/web-greeter#20]
WindowsXP theme also does not work. Can you fix that too please? https://github.com/mshernandez5/WelcomeXP

**Comment by JezerM** [comment]
I'm not a theme fixer, that should be opt to the theme owners xd

But I'll try~

**Comment by JezerM** [comment]
I made a [fork](https://github.com/JezerM/WelcomeXP) and fixed the problems I got. You can check the PR [here](https://github.com/mshernandez5/WelcomeXP/pull/9).

**Comment by JezerM** [comment]
The Pull Request was merged, and so the WindowsXP theme is available for web-greeter and nody-greeter.
