### ISSUE TITLE
Right click greeter shows artifacts

### ISSUE THREAD

**Issue by doankimhuy-it** [JezerM/web-greeter#27]
## Environment
- OS: Ubuntu MATE 21.10
- web-greeter version: 3.2.1

## Bug description
Right click and greeter show a menu, hovering over items and artifacts appear for about a second.

## Steps to reproduce
Right click greeter (I use gruvbox).
Hover mouse through items in list.

## Expected behavior
No artifacts or disable right click.

**Comment by JezerM** [comment]
It should be fixed now on latest commit: dc6b2f2d. Right click context menu should only appear on debug-mode.

**Comment by doankimhuy-it** [comment]
It is now gone, thank you.
