### ISSUE TITLE
Which versions of JavaScript, HTML and CSS are supported?

### ISSUE THREAD

**Issue by BobbyBabes** [JezerM/web-greeter#28]
As per the title.

**Comment by JezerM** [comment]
This depends on the chromium version QtWebEngine ships with. You can see a [versions table](https://wiki.qt.io/QtWebEngine/ChromiumVersions) in the Qt documentation, then you would need to check your current `Qt5Core` and `QtWebEngine` versions. The expected features are attached to the lower version between these two; if using QtWebEngine 5.15.8 but QtCore 5.15.2, then your current version is 5.15.2.

The most common version is the 5.15.2, so it means web-greeter uses Chromium v83. Therefore, you can expect the following features:

- ES6 for JavaScript.
- HTML5 (as every modern browser)
- CSS3 (as every modern browser)

CSS in Chromium v83 it's more outdated than JavaScript, as features like Flexbox gaps are not available. Check [caniuse](https://caniuse.com/?compare=chrome+83&compareCats=CSS,HTML5,JS,JS%20API,Other,Security,SVG) for more information.

**Comment by BobbyBabes** [comment]
On a fully updated Arch Linux I find the following. Assuming the directory names are correct, you are spot on with version 5.15.2. Thanks a lot. In the new year, I'm going to read into the docs linked from the versions table page that you linked. Thanks a lot for this information. And I wish you a Happy New Year. All the best.
```
/usr/include/qt/QtWebEngine/QtWebEngine
/usr/include/qt/QtWebEngine/5.15.7/QtWebEngine

/usr/include/qt/QtWebEngine/QtWebEngine
/usr/include/qt/QtWebEngine/5.15.7/QtWebEngine

/usr/include/qt/QtCore/QtCore
/usr/include/qt/QtCore/5.15.2/QtCore
```

**Comment by JezerM** [comment]
So, according to the table, the chromium version you're using is v83, as expected~

Have a happy new year!
