### ISSUE TITLE
Adding active-monitor 

### ISSUE THREAD

**Issue by 112RG** [JezerM/web-greeter#29]
## Environment
- OS: Arch latest
- web-greeter version: 3.2.0

## Description of feature
Adding the active-monitor config option from webkit2-greeter.

I have for days been trying to get webkit-greeter to start on my main monitor to no avail.
Using commands such as ``xrandr --output DP-4 --auto --primary --output DP-0 --auto --right-of DP-4 --output DP-2 --auto --left-of DP-4`` in a display-setup-script only leads to all my monitors flickering on and off displaying nothring. I am using nvidia drivers too. And active-monitor is the only option that has worked for getting lightdm displayed on the correct screen
## Possible solutions
Cant think of any

**Comment by JezerM** [comment]
Did webkit2-greeter have a `active-monitor` option? I don't think so. **lightdm-gtk-greeter** is the one that has this feature, though~

About adding this feature, I don't have a multi-monitor setup, so it would be impossible for me to test it, sadly.

**Comment by 112RG** [comment]
Oh you know its weird that ``active-monitor`` worked even when I wasn't using lightdm gtk. I might poke around the code and see how it works to see if its possible. Since xrandr seems to not be a option

**Comment by JezerM** [comment]
You can check if #35 does work in your case. There is no `active-monitor` option, but it should detect your main/primary monitor to show web-greeter's window.
