### ISSUE TITLE
Screen flickers before loading theme

### ISSUE THREAD

**Issue by pwall2222** [JezerM/web-greeter#3]
This started happening randomly, I reinstalled it and still does it. The logs say nothing about it. I wiped everything reinstalled everything and the problem still ocours. It both happens on debugging when loged in and when logging in for the first time.

**Comment by JezerM** [comment]
Hmm, that's weird. Can you provide screenshots or photos?

**Comment by pwall2222** [comment]
https://streamable.com/t2pxe8
A whole video with the flicker effect, it also happens when first logging in but thats too hard to capture.

**Comment by JezerM** [comment]
Oh, it's not screen flickering per se. The greeter shows first a white screen, like a simple browser would do, then it loads the theme. It's annoying.
It could be fixable, though.
Then, backgrounds "flickering" it's normal in webpages.

I'll check this out.

**Comment by pwall2222** [comment]
I don't remember it doing it before though? My memory is too bad to remember though. It gets really annoying when you just got from a dark screen, and I have tried not loadings any html and the white still shows so no idea.

**Comment by JezerM** [comment]
The white screen is default by the greeter, so no theme would do anything to fix it.
As an early idea, it would be just to change the QApplication background color to black.

**Comment by JezerM** [comment]
Ok, it was quite easy. I updated the master branch with this fix.
If you did install the 3.0.0rc3 before, updating to 3.0.0rc4 would need to install the [latest whither release](https://github.com/JezerM/whither/releases/tag/0.3.4).

**Comment by JezerM** [comment]
Should look like this: https://streamable.com/ufzmaw

**Comment by pwall2222** [comment]
I have nothing to pull, I have the 0.3.4v installed (reinstalled it to check just in case) and still got that issue.

**Comment by pwall2222** [comment]
It works now, thank you so much!
