### ISSUE TITLE
Cant login using the glorious theme

### ISSUE THREAD

**Issue by Crylia** [JezerM/web-greeter#33]
## Environment
- OS: Pop_OS! 21.10
- web-greeter version: 3.3.0

## Bug description
When trying to login (hitting enter or the login button) nothing happens

## Steps to reproduce
Download the glorious theme and try to login

## Expected behavior
Login to work

**Comment by JezerM** [comment]
Run `web-greeter --debug` and provide the log. However, it's possible that this error could be related to [this other error](https://github.com/manilarome/lightdm-webkit2-theme-glorious/issues/68).

The Glorious theme is unmaintained, so don't expect it to work flawlessly. There are some Pull Requests about this issue, so you could clone one and try it.

Also, I do have a [fork](https://github.com/JezerM/lightdm-webkit2-theme-glorious) of this theme, which should work. However, the translation feature is not implemented in this one.
