### ISSUE TITLE
Theme - suggestion

### ISSUE THREAD

**Issue by gene-git** [JezerM/web-greeter#38]
Couple of thoughts from a new user:

1) The default grucbox theme doesn't have the background image selector option - at least for me. MIght be better to have that or change default to dracula

2) I think it would be nice to include the web-greeter-theme-luminosity theme in your distribution?
https://github.com/rda0/web-greeter-theme-luminosity

3) To encourage and expand the available themes, would it make sense to create a place for themes to reside?  I'm thinking something like a separate github web-greeter-themes area.  Building a good theme base will likely expand your user base as well. 

The setup here is Arch Linux with plasma wayland by default.  We're exploring replacing sddm with web-greeter.
I also made a suggested edit to AUR package to avoid absolute paths in package. 

Thank you for working on this and keeping it updated.

**Comment by gene-git** [comment]
Excellent thank you - will pull now.

**Comment by gene-git** [comment]
Yes agree on them owner controlling the decision - thank you again! I'm in process of testing before packaging up for local use.

**Comment by gene-git** [comment]
Thank you again!

**Comment by rda0** [comment]
> > I think it would be nice to include the web-greeter-theme-luminosity theme in your distribution?
> 
> It would be cool, however I prefer to have minimal and functional themes that could even help to develop new themes. Also, this should be the theme owner/maintainer's decision to wheter include their theme or not; it's not my decision~

I have the same opinion. The code should really not serve as an example, it just works and unfortunately I have no time or skill to improve it. But anyone, please feel free to include, fork or link to it 👍

**Comment by JezerM** [comment]
I just bumped web-greeter to 3.4.1, and updated the AUR package to this new version, which uses the improved build process and should be less prone to errors.

**Comment by gene-git** [comment]
Thank you for staying on top of this @JezerM

**Comment by JezerM** [comment]
Previously, I had a [web-greeter-themes](https://github.com/JezerM/web-greeter-themes) repo, which serves as a Live Demo for the default themes, so instead I created another repo: [web-greeter-page](https://github.com/JezerM/web-greeter-page), that would contain the greeters' info, and the Community themes.

I've been working on web-greeter-page for the last 4 days, and although I still need to work a bit on the design, it's kinda complete and functional~

See the webpage here: https://jezerm.github.io/web-greeter-page/

**Comment by JezerM** [comment]
Background selector was added to gruvbox theme in both web-greeter and nody-greeter~

**Comment by gene-git** [comment]
great thanks!
