### ISSUE TITLE
Where to put avatar icons?

### ISSUE THREAD

**Issue by mocdaniel** [JezerM/web-greeter#39]
Hi, 

I'm facing problems setting my avatar icon. I prepared a 96x96 .png file and tried the possible solutions mentioned in the [ArchWiki section of LightDM](https://wiki.archlinux.org/title/LightDM#Changing_your_avatar) but neither way worked.

I tried putting my picture named `.face` and permissions `0644` at `/home/daniel/.face` as well as putting it at `/var/lib/accountsservice/icons/daniel.png` and edited `/var/lib/accountsservice/users/daniel` accordingly, neither way works.

It seems like web-greeter does not pick up on the configuration, do I have to edit `lightdm.conf` or `web-greeter.yml` as well? 

Thx in advance and best regards,
Daniel

**Comment by JezerM** [comment]
Greetings~

A `.face` generally works when you are logged in, but LightDM doesn't have the permissions to read inside your home directory, so it won't work. It's preferred to put your icon at `/var/lib/AccountsService/icons/daniel` (maybe, try to remove the `.png` extension) and edit `/var/lib/AccountsService/users/daniel` to use the previously added icon, with the permissions set to `644` and owned by root.

It's not needed to edit `lightdm.conf` neither `web-greeter.yml`. If this doesn't work, I have a few questions:

- Does your avatar icon show in other programs, like your DE settings manager, mugshot, or a Display Manager like gdm?
- What theme are you using? Does this occurs with all web-greeter themes?

**Comment by mocdaniel** [comment]
Thank you very much, I got it solved with the information you provided. The culprit was wrong permissions/ownership of the image and the config file, probably.
