### ISSUE TITLE
Update DEBIAN/control version

### ISSUE THREAD

**Issue by rda0** [JezerM/web-greeter#40]
The debian/ubuntu package version in the `DEBIAN/control` file in web-greeter-3.4.1-ubuntu.deb still lists the package as version 3.4.0:

```
ii  web-greeter                                   3.4.0                                      all          A modern, visually appealing greeter for LightDM.

**Comment by JezerM** [comment]
Oh, sure, I'll fix it soon~

**Comment by JezerM** [comment]
It should be done in bfab72f03 :D
