### ISSUE TITLE
AUR install broken

### ISSUE THREAD

**Issue by ProspectPyxis** [JezerM/web-greeter#44]
## Environment
- OS: Arch Linux
- web-greeter version: N/A, but trying to install 3.4.1-2

## Bug description
The AUR package seems to have a broken checksum:
```
==> Making package: web-greeter 3.4.1-2 (Tue 07 Jun 2022 04:08:17 PM +07)
==> Checking​ runtime dependencies... 
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found web-greeter-3.4.1.tar.gz
  -> Found package.patch
==> Validating source files with sha512sums...
    web-greeter-3.4.1.tar.gz ... FAILED
    package.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
```

## Steps to reproduce
1. `git clone https://aur.archlinux.org/web-greeter.git`
2. `cd web-greeter`
3. `makepkg -s`
4. It should throw the above error

## Expected behavior
The program should install correctly.

**Comment by JezerM** [comment]
I see, I'll try to fix it soon~

**Comment by JezerM** [comment]
Sha512sum fixed, now it should be installed correctly :D
