### ISSUE TITLE
Need session selection menu.

### ISSUE THREAD

**Issue by aloksrk** [JezerM/web-greeter#45]
OS: Archlinux
Need session selection menu. I want to start Gnome Wayland as default, but greeter always start xsessions.

**Comment by JezerM** [comment]
Which theme are you using? If **gruvbox**, there's a session selector in the top-left blue button; if **dracula**, the bottom-left button that shows the current selected session is a session selector~

However, there's an issue with LightDM where you cannot specify whether you want the X session or the Wayland one. So, if you're having this problem, try to modify your x-session and wayland-session at `/usr/share/xsessions/` and `/usr/share/wayland-sessions/` respectively:

1. Change the file name. LightDM uses the file name as a key, which is used to start the session. If you have a `gnome.desktop` in `xsessions` and a `gnome.desktop` in `wayland-sessions`, LightDM won't recognize which one you're trying to use and will start the xsession by default. So, I'd recommend to rename the one in `wayland-sessions` as `gnome-wayland.desktop` or similar, just make sure there is no other desktop with the same name.
2. Change the name of your desktop. This step is optional, but can be useful when presenting the session in the greeter. Edit your desired session, for example `gnome-wayland.desktop`, search for `Name=Gnome` and change it for something like `Name=Gnome (Wayland)`; you could do the same to the xsession one: from `Name=Gnome` to `Name=Gnome (X11)`.
