### ISSUE TITLE
web-greeter does not remember last used session by user

### ISSUE THREAD

**Issue by cycomanic** [JezerM/web-greeter#52]
Not sure if this should be a feature request or a bug, I report as bug here. 

## Environment
- OS:  Arch
- web-greeter version: 3.5.1

## Bug description

web-greeter does not remember the last used session for a user in a multi-user system (if users use different sessions). 

## Steps to reproduce
Use web-greeter on a multi-user system. Use two different sessions for e.g. user A and B. Changing from user A to user B in the interface keeps the session of user A selected, even though user B always logs in with a different session. 

Example:
User A always uses gnome, user B uses sway. User B has been using the sway and logs out to get back to lightdm. User A now wants to use the computer and selects their user -> Session type stays as sway and user B needs to select gnome for correct login.

## Expected behavior
The last used session should be remember per user. It seems lightdm saves these in the standard location (~/.dmrc), but the information is not used by web-greeter

**Comment by JezerM** [comment]
Which theme are you using? Generally it depends how the theme was built.

Some themes like gruvbox and dracula saves the last session inside the browser LocalStorage, so your last logged-in session will always be selected no matter which user you are going to log-in. Some others (I don't remember one right now) may use your AccountsService data to select your default session, which is what you expect.

I could consider this as a feature request, as the functionality is already provided by web-greeter but it's not being used xd

**Comment by SpyrosRoum** [comment]
I am using the default (looks like Gruvbox) and it still doesn't remember what I last logged in with.

OS: Arch
version: 3.5.1

**Comment by JezerM** [comment]
Okay, I will fix it soon (when I have time).

**Comment by raven2cz** [comment]
I installed web-greeter yesterday and I have some problem. The previous session isn't restore, first from list is taken. I have just one user account. Arch is used too. It seems that it will be similar settings as OP.

Just for information, why I have to change by lightdm theme yesterday. There is new issue 

https://bbs.archlinux.org/viewtopic.php?id=279862

New version of `webkit2gtk` kills authentication method older web-greeter lib `lightdm-webkit2` and it seems that all older themes stop working now. For example `lightdm-webkit2-theme-glorious`. 

Your web-greeter and themes still works!

**Comment by JezerM** [comment]
This should be fixed now in https://github.com/JezerM/web-greeter-themes/commit/179acb6c0305deebfb49d260857ea1f3d1aa190a latest commit in both Gruvbox and Dracula theme. Do a `git pull` in your web-greeter cloned directory and install web-greeter again~

Whenever you change your selected user, Gruvbox and Dracula theme will also select your user's default session (which is typically your last logged-in session); if it doesn't encounter one, the lightdm's default session will be used.
