### ISSUE TITLE
Upgrade via Arch AUR overwrites web-greeter.yml

### ISSUE THREAD

**Issue by Bouni** [JezerM/web-greeter#59]
## Environment
- OS: Arch linux
- web-greeter version: 3.5.1

## Bug description

After upgrading my web-greeter.yaml was overwritten.

## Steps to reproduce

Upgrade web-greeter with `yay -S web-greeter`

## Expected behavior

Keep the existing web-greeter.yaml

**Comment by JezerM** [comment]
It should be fixed now in the latest web-greeter release for the AUR: `3.5.2_2`
