### ISSUE TITLE
/usr/share/web-greeter/themes/simple/index.yml exists in filesystem

### ISSUE THREAD

**Issue by Bouni** [JezerM/web-greeter#60]
## Environment
- OS: Arch linux
- web-greeter version: 3.5.1

## Bug description

When I try to upgrade via `yay -Syu` the upgrade fails with this output:

```sh
(1/1) checking keys in keyring                                                                                                  [#############################################################################] 100%
(1/1) checking package integrity                                                                                                [#############################################################################] 100%
(1/1) loading package files                                                                                                     [#############################################################################] 100%
(1/1) checking for file conflicts                                                                                               [#############################################################################] 100%
error: failed to commit transaction (conflicting files)
web-greeter: /usr/share/web-greeter/themes/simple/index.yml exists in filesystem
Errors occurred, no packages were upgraded.
 -> exit status 1
```

## Steps to reproduce

Upgrade from 3.5.1 to 3.5.2

## Expected behavior

Upgrade without error 😄

**Comment by Bouni** [comment]
I force installed the upgrade with `yay -Syu --overwrite "*"` but thats not the plan, right 😏

**Comment by JezerM** [comment]
I tried to replicate this error, but it always succeeded correctly. Maybe you did install web-greeter without the AUR? Or perhaps, you did install web-greeter-3.5.1_1 which did some weird workarounds in the build system to install the themes, and somehow it affected the upgrade to 3.5.2. However, this shouldn't happen in newer updates.

**Comment by Bouni** [comment]
> Or perhaps, you did install web-greeter-3.5.1_1

Possible, I can't say for sure. I'll just see what happens with the next update and re-open the issue if the problem occures again.
