### ISSUE TITLE
Litarvan theme giving errors

### ISSUE THREAD

**Issue by chiranchimmili** [JezerM/web-greeter#61]
## Environment
- OS: Arch
- web-greeter version: latest

## Bug description
Getting "TypeError" messages when using Litarvan theme, other themes like dacula are working properly.
Using latest version of Litarvan (3.2.0). 

First a black screen emerges in the first screenshot, if I press reload, the 2nd screenshot screen comes but with the first error message. I press cancel next and get second error message. Pressing cancel again results in blurry screen with no login prompt.

## **Screenshots**
![image](https://user-images.githubusercontent.com/82386370/213579290-258c2b68-c7f0-4c1c-a12a-3860e986087d.png)
![image](https://user-images.githubusercontent.com/82386370/213579308-acd497f3-104f-4e5a-87b3-86ff29c6917c.png)

**Comment by JezerM** [comment]
The latest version of Litarvan theme is not web-greeter compatible. Use the master version instead, which includes some patches to make it work for web-greeter and nody-greeter.
