### ISSUE TITLE
unable to start normally

### ISSUE THREAD

**Issue by PurpleRed-River** [JezerM/web-greeter#65]
## environment
- OS: Arch 6.4.4-zen1
web-greeter installed via AUR

## wrong description
unable to start normally

## **debug screenshot**
![1689991142130](https://github.com/JezerM/web-greeter/assets/93107316/022a75ce-8c68-4afc-bf76-a3ceb7a276ec)

**Comment by JezerM** [comment]
It looks like you're trying to run web-greeter from a TTY. Web-greeter needs an X11 Display to be executed on, so that's why it shows that QT couldn't connect to display.
