### ISSUE TITLE
opensuse tumbleweed make: tsc: no such file or directory

### ISSUE THREAD

**Issue by VoidYin** [JezerM/web-greeter#67]
## Environment
- OS: opensuse tumbleweed
- web-greeter version: 3.5.2

## Bug description
sudo make install
error:
make: tsc: no such file or directory

## solution
sudo ln -s /usr/local/bin/tsc /usr/bin/tsc

**Comment by JezerM** [comment]
This is not a web-greeter bug, but a `PATH` issue.
