### ISSUE TITLE
Incorrect Cursor Shape After Moving Mouse

### ISSUE THREAD

**Issue by corigne** [JezerM/web-greeter#79]
## Environment
- OS: Arch Linux x86_64, Kernel 6.8.7-arch1-1
- web-greeter version: 3.5.3

## Bug description
When loading into the greeter, the primary cursor is displayed correctly until you move the mouse. Then, the primary cursor changes a semi-transparent dark grey circle with a slightly lighter outline. If you right-click, the correct cursor theme is visible, so the correct cursor theme is being applied from the configuration file. I have verified the cursors are installed in /usr/share/icons and are available to the system. They work in both my dm (i3) and other applications. It almost seems like the cursor thinks the system is receiving touch-screen input, but that's a guess and isn't based on any hard evidence. I have no tablets or touch-screen attached to this device.

## Steps to reproduce
1. Set any cursor theme as the cursor theme in the web-greeter.yml file.
2. Run `web-greeter --debug` in the terminal.
3. Move the mouse.
4. The cursor is now a dark circle with slightly lighter outline.

## Expected behavior
The cursor from the specified cursor/icon theme should be visible even after moving the mouse.

## **Screenshots**
Test with WelcomeXP theme (my usual theme):
![image](https://github.com/JezerM/web-greeter/assets/7695563/8fcb15da-a45d-4796-bfdc-d0d2bf9974d7)

Test with included dracula theme:
![image](https://github.com/JezerM/web-greeter/assets/7695563/cda88a71-1c1e-421f-a618-060acf38f683)

**Comment by corigne** [comment]
On a hunch I changed the greeter mode to debug = false  and this fixed the issue. I wasn't aware debug mode affected the cursor. I will do some more testing and then close the ticket if all is well.

**Comment by JezerM** [comment]
Hi! This issue is caused by debug mode, as you noted. By default, when enabling the inspector in Chromium the Device Toolbar is enabled and so the browser acts like a Touch device.

**Comment by corigne** [comment]
Appreciate the feedback. Marking closed due to user error!
