### ISSUE TITLE
theme not applying on logout ?

### ISSUE THREAD

**Issue by Ryder17z** [JezerM/web-greeter#82]
## Environment
- OS: Endeavour
![image](https://github.com/user-attachments/assets/56bf5d19-b61e-4ca5-9a36-26a425cb21d0)
- web-greeter version: output of `web-greeter --version` 3.5.3

## Bug description
When logging out, I am not greeted by the [Shikai](https://github.com/TheWisker/Shikai) theme.
I am greeted by it on boot however.

Not sure where to find the log or if it's needed.

## Steps to reproduce
Unknown.
* I started out with SDDM but that has been disabled so I could switch to LightDM.

## Expected behavior
Use same theme when I log out as i do when i first log in.

## **Screenshots**
N/A

**Comment by JezerM** [comment]
Hi! Could you share the log at `/var/log/lightdm/seat0-greeter.log`? As well as `/var/log/lightdm/lightdm.log`

**Comment by Ryder17z** [comment]
> Hi! Could you share the log at `/var/log/lightdm/seat0-greeter.log`? As well as `/var/log/lightdm/lightdm.log`

Hi, it seems to be resolved by a system update. Last time I encountered the issue was a few days ago but I can't easily reproduce it anymore.

**Comment by Ryder17z** [comment]
[lightdm.log](https://github.com/user-attachments/files/16369456/lightdm.log)
[seat0-greeter.log](https://github.com/user-attachments/files/16369457/seat0-greeter.log)

**Comment by JezerM** [comment]
Hmm, everything seems alright in those logs, and as it's not happening anymore, I'll close the issue. If the issue happens again in the future, reopen this and provide the logs~

**Comment by Ryder17z** [comment]
Except for on resume-from-sleep as stated.

**Comment by JezerM** [comment]
Only to copy the logs after resume-from-sleep. Switch to a TTY and copy them to any directory, them submit them~

**Comment by Ryder17z** [comment]
logs seem no different from before. Sharing them in case i missed something.

[lightdm.log](https://github.com/user-attachments/files/16445657/lightdm.log)
[seat0-greeter.log](https://github.com/user-attachments/files/16445658/seat0-greeter.log)

**Comment by Ryder17z** [comment]
The issue is persisting and I haven't found a solution.

**Comment by Ryder17z** [comment]
https://github.com/canonical/lightdm/issues/99   might be related?
