### ISSUE TITLE
Unable to access to the Avatar Image

### ISSUE THREAD

**Issue by lesebas** [JezerM/web-greeter#83]
Hello, I'm trying to migrate the petrichor theme from webkit2 to web-greeter. (https://github.com/phillid/petrichor/tree/master). The code to update the icon of each user into petrichor.js (same as main.js) is as below : 

var html = "";
	for (i in lightdm.users)
	{
		user = lightdm.users[i];

		if (user.image == null || user.image.match(/\.face$/))
			image = '/usr/share/icons/Adwaita/256x256/emotes/face-laugh.png';
		else
			image = user.image;

		html += '<a href="#" class="user" id="user-' + user.name +'" onclick="start_authentication(\'' + user.name + '\')">';
		html += '<img class="avatar" src="file:///' + image + '" /><span class="name">'+user.display_name+'</span>';

		if (user.name == lightdm.autologin_user && lightdm.autologin_timeout > 0)
			html += '<span id="countdown-label"></span>';

		html += '</a>';
	}

	document.getElementById('users').innerHTML = html;

The default Image is not working but it's normal as I should use the default image defined into web-greeter.yml

However the html section added into the web page do not work even if an icon is defined for the user. I receive an error message as the html page cannot access to /var/lib/AccountsService/icons/username.png.

Any idea to help me?

**Comment by TheWisker** [comment]
I also had some problems accessing the avatar images.
If it helps here is what I did to solve them:
- The folder where the image reside must either have read and execute permission for others or an ACL entry for lighdm user or lighdm group to give read and execute permission
- The same step for the .face image
I hope it helps!

**Comment by JezerM** [comment]
Same comment as Wisker, make sure that the directory and each image inside `/var/lib/AccountsService/icons` have read and execute permissions for everyone.

**Comment by lesebas** [comment]
Hello,

I've tried to change the permissions of the folder/file but it not helps :


```
[sebastien@FivesVMArchlinux ~]$ sudo getfacl /var/lib/AccountsService/icons/
[sudo] Mot de passe de sebastien : 
getfacl : suppression du premier « / » des noms de chemins absolus
# file: var/lib/AccountsService/icons/
# owner: root
# group: root
user::rwx
user:lightdm:rwx
group::rwx
group:lightdm:rwx
mask::rwx
other::rwx

[sebastien@FivesVMArchlinux ~]$ sudo getfacl /var/lib/AccountsService/icons/sebastien 
getfacl : suppression du premier « / » des noms de chemins absolus
# file: var/lib/AccountsService/icons/sebastien
# owner: root
# group: root
user::rw-
user:lightdm:rwx
group::r--
group:lightdm:rwx
mask::rwx
other::rwx
```


![Image](https://github.com/user-attachments/assets/2d03bc87-3d25-43bb-826a-08a05441f73e)

**Comment by JezerM** [comment]
I see that you're using "petrichor" theme, is this one right here: https://github.com/phillid/petrichor? If so, I must say that it's pretty outdated and shouldn't be used.

There's this line at [petrichor.js#L159](https://github.com/phillid/petrichor/blob/8074f7d7333bb538429cff7511a9954ac2e1efc6/petrichor.js#L159) where it sets the image src to `file:///` plus the user image. Access to files via `file://` protocol is prohibited in web-greeter, so it always fails to load the image. You could remove this protocol at that line and it should be fixed:

```diff
- html += '<img class="avatar" src="file:///' + image + '" /><span class="name">'+user.display_name+'</span>';
+ html += '<img class="avatar" src="' + image + '" /><span class="name">'+user.display_name+'</span>';
```

**Comment by lesebas** [comment]
OK I will try many thanks.
Yes I know that Petrichor is outdated, that's why I'm trying to update it. I have some notion of programming but I'm not a specialist so far. Thanks again for your help.
