### ISSUE TITLE
Hide the cog / Prevent background change without authentication

### ISSUE THREAD

**Issue by K0-RR** [JezerM/web-greeter#85]
## Description of feature
To stop just anyone from changing the wallpaper and to achieve a cleaner UI, a config option to disable this feature is awaited.

Or maybe this action can be password-protected?

**Comment by JezerM** [comment]
Hi, you can always edit the source code for all themes. For this specific change, you can edit the index.html file and remove the following lines (104-106):

```html
      <button id="background-selector-enter" type="button" class="button">
        <span class="mdi mdi-cog"></span>
      </button>
```

https://github.com/JezerM/web-greeter-themes/blob/44283cafccece5366612301d927fe5628fe9eda1/themes/gruvbox/index.html#L104-L106

This way, the button won't appear and changing the wallpaper won't be possible.

**Comment by JezerM** [comment]
Changing the wallpaper is a theme feature, hence I can't enforce this feature from web-greeter.
